Repository sonia-auv/sonia-behaviors, pull requests merged in 2022-07, with the labels that each got.

#29 Feature/underwater com
  sonia_com_states/CMakeLists.txt
  sonia_com_states/package.xml
  sonia_com_states/setup.py
  sonia_com_states/src/sonia_com_states/__init__.py
  sonia_com_states/src/sonia_com_states/choose_your_character.py
  sonia_com_states/src/sonia_com_states/get_update.py
  sonia_com_states/src/sonia_com_states/modules/__init__.py
  sonia_com_states/src/sonia_com_states/modules/com_utilities.py
  sonia_com_states/src/sonia_com_states/send_update.py
  sonia_com_states/src/sonia_com_states/synchro_master.py
  sonia_com_states/src/sonia_com_states/synchro_receive.py
  sonia_com_states/src/sonia_com_states/synchro_send.py
  sonia_com_states/src/sonia_com_states/takeover_mission.py
  sonia_flexbe_behaviors/manifest/synchro_master.xml
  sonia_flexbe_behaviors/manifest/test_addpose.xml
  sonia_flexbe_behaviors/manifest/test_bag.xml
  sonia_flexbe_behaviors/manifest/test_move.xml
  sonia_flexbe_behaviors/manifest/test_pool_synchro_master.xml
  sonia_flexbe_behaviors/manifest/test_proc_fault.xml
  sonia_flexbe_behaviors/manifest/test_trajectory.xml
  sonia_flexbe_behaviors/manifest/test_yaw_orbit.xml
  sonia_flexbe_behaviors/manifest/test_zigzag.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/move_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/search_snake_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/synchro_master_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_bag_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_move_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_pool_synchro_master_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_proc_fault_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_trajectory_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_zigzag_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_path_new_algo_sm.py
  sonia_hardware_states/src/sonia_hardware_states/module_check.py
Labels: Priority: High, Type: Feature

#35 Feature/bags buoys bins
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/mission_bags_bins_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/mission_bags_buoys_sm.py
Labels: Priority: High

#39 Feature/mission intercom
  sonia_flexbe_behaviors/manifest/auv8_auv7_run_coinflip_gate_with_trick_path.xml
  sonia_flexbe_behaviors/manifest/auv8_auv7_test_piscine_francis.xml
  sonia_flexbe_behaviors/manifest/coin_flip_ky.xml
  sonia_flexbe_behaviors/manifest/move_to_gate_straight.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/auv8_auv7_run_coinflip_gate_with_trick_path_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/auv8_auv7_test_piscine_francis_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/coin_flip_ky_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/move_to_gate_straight_sm.py
Labels: Priority: High, Type: Feature

#41 Feature/mission intercom
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/auv8_auv7_run_coinflip_gate_with_trick_path_sm.py
Labels: Priority: High, Type: Feature

#53 added max and min mouvement as parameters
  .github/pull_request_template.md
  sonia_flexbe_behaviors/manifest/vision_bins.xml
  sonia_flexbe_behaviors/manifest/vision_buoy.xml
  sonia_flexbe_behaviors/manifest/vision_droppers.xml
  sonia_flexbe_behaviors/manifest/vision_tables.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_bins_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_buoy_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_droppers_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_tables_sm.py
  sonia_hardware_states/src/sonia_hardware_states/activate_io.py
  sonia_vision_states/src/sonia_vision_states/get_simple_vision_target.py
Labels: Priority: High, Type: Enhancement

#56 fix coinflip gate outcomes. remove broken behavior
  sonia_flexbe_behaviors/manifest/auv8_auv7_run_coinflip_gate_with_trick_path.xml
  sonia_flexbe_behaviors/manifest/auv8_auv7_test_piscine_francis.xml
  sonia_flexbe_behaviors/manifest/test_pool_synchro_master.xml
  sonia_flexbe_behaviors/manifest/test_synchro.xml
  sonia_flexbe_behaviors/manifest/trickshot.xml
  sonia_flexbe_behaviors/manifest/trickshot_with_com.xml
  sonia_flexbe_behaviors/manifest/trickshot_yaw.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/auv8_auv7_run_coinflip_gate_with_trick_path_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/auv8_auv7_test_piscine_francis_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/coinflip_gate_with_com_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_pool_synchro_master_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/test_synchro_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/trickshot_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/trickshot_with_com_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/trickshot_yaw_sm.py
  sonia_navigation_states/src/sonia_navigation_states/trick_shot.py
Labels: Priority: High, Type: Feature

#60 change z in absolute for avoid_buoys mission
  sonia_flexbe_behaviors/manifest/avoid_buoys_after_collision.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/avoid_buoys_after_collision_sm.py
Labels: Priority: Medium

#65 Feature/com improvements
  sonia_com_states/src/sonia_com_states/takeover_mission.py
  sonia_flexbe_behaviors/manifest/coinflip_gate_trickshot_with_com.xml
  sonia_flexbe_behaviors/manifest/coinflip_gate_with_com.xml
  sonia_flexbe_behaviors/manifest/init_submarine_with_com.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/coinflip_gate_trickshot_with_com_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/coinflip_gate_with_com_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/init_submarine_with_com_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/trickshot_with_com_sm.py
Labels: Priority: High, Type: Feature

#73 Feature/activation behavior
  sonia_flexbe_behaviors/manifest/avoid_buoys_after_collision.xml
  sonia_flexbe_behaviors/manifest/drop_auv7.xml
  sonia_flexbe_behaviors/manifest/drop_auv8.xml
  sonia_flexbe_behaviors/manifest/vision_bins.xml
  sonia_flexbe_behaviors/manifest/vision_buoys.xml
  sonia_flexbe_behaviors/manifest/vision_droppers.xml
  sonia_flexbe_behaviors/manifest/vision_path.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/avoid_buoys_after_collision_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/drop_auv7_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/drop_auv8_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_bins_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_buoys_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_droppers_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_path_sm.py
  sonia_flexbe_states/src/sonia_flexbe_states/activate_behavior.py
Labels: Priority: High

#75 Feature/add enum filterchain
  sonia_flexbe_behaviors/manifest/vision_bins.xml
  sonia_flexbe_behaviors/manifest/vision_buoys.xml
  sonia_flexbe_behaviors/manifest/vision_droppers.xml
  sonia_flexbe_behaviors/manifest/vision_path.xml
  sonia_flexbe_behaviors/manifest/vision_tables.xml
  sonia_flexbe_behaviors/manifest/vision_torpedoes.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_bins_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_buoys_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_droppers_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_path_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_tables_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_torpedoes_sm.py
Labels: Priority: High

#84 all working in simulation except droppers
  sonia_flexbe_behaviors/manifest/vision_bins.xml
  sonia_flexbe_behaviors/manifest/vision_buoys.xml
  sonia_flexbe_behaviors/manifest/vision_path.xml
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_bins_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_buoys_sm.py
  sonia_flexbe_behaviors/src/sonia_flexbe_behaviors/vision_path_sm.py
Labels: Priority: Critical, Type: Bug, Type: Enhancement
